### ISSUE TITLE
atk-reaper example sessions

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/ambisonictoolkit.github.io#17]
Make available atk-reaper example sessions.

This will better align atk-reaper with atk-sc3. At a first step, recreating some of the atk-sc3 examples using [atk-sounds](https://github.com/ambisonictoolkit/atk-sounds) could be useful.

**Comment by lossius** [comment]
As I go ahead and add video tutorials for ATK Reaper, I'll add the resulting Reaper projects to https://github.com/ambisonictoolkit/atk-reaper-examples . I've already made a first 0.0.1 release and made a download button on the "ATK for Reaper - Tutorials" page.

I'll close this issue now, as I from here on will start making more specific issues detailing the content of each tutorial. I'll post those issues in this rep rather than https://github.com/ambisonictoolkit/atk-reaper so that they can be referenced in future commits with updates to the website.

**Comment by joslloand** [comment]
@lossius sounds like a good strategy!
